version: "3.8"
services:
  backend-flask:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=main.py
      - FLASK_RUN_HOST=0.0.0.0
      - FRONTEND_URL=http://localhost:5173
      - BACKEND_URL=http://localhost:5000
    volumes:
      - ./backend/instance:/app/instance

  frontend-react-js:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:5000
    command: npm run dev -- --host 0.0.0.0